services:
  mc:
    image: itzg/minecraft-server:java21
    ports:
      - 25565:25565
    tty: true
    stdin_open: true
    environment:
      EULA: true
      MAX_MEMORY: 11000M
      VIEW_DISTANCE: 16
      SIMULATION_DISTANCE: 12
      USE_AIKAR_FLAGS: true
      ONLINE_MODE: false
      MOTD: "\u00a74\u00a7l\u00a7kyy\u00a74\u00a7l\u0412\u043e\u043d\u043e \u043d\u0430\u0440\u043e\u0434\u0438\u043b\u043e\u0441\u044f\u00a74\u00a7l\u00a7kyy"
      ENABLE_WHITELIST: true
      ENFORCE_SECURE_PROFILE: false
      DIFFICULTY: hard
      VERSION: 1.20.1
      TYPE: FORGE
      RCON_CMDS_STARTUP: |-
        gamerule playersSleepingPercentage 50
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./data:/data
