name = "minecraft-cenechat-kings"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4eb637b87bf23861af0419db6dd6fbe63b0dcdff28d4210eb9d2bab7aeddf33"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
