#Recruits Config:
[Recruits]
	#
	#Max amount a player can recruit
	#	(takes effect after restart)
	#	default: 64
	#Range: 1 ~ 1453
	MaxRecruitsForPlayer = 40
	#
	#List of foods that recruits should not eat.
	#	(takes effect after restart)
	#	Food items in this list will not be eaten by recruits and also not be picked up from upkeep.
	FoodBlackList = ["minecraft:poisonous_potato", "minecraft:spider_eye", "minecraft:pufferfish"]
	#
	#Mount Whitelist
	#	(takes effect after restart)
	#	ONLY Entities in this list can be mounted by a recruit, for example: ["minecraft:boat", "smallships:cog", ...]
	MountWhitelist = ["minecraft:mule", "minecraft:donkey", "minecraft:horse", "minecraft:llama", "minecraft:pig", "minecraft:boat", "minecraft:minecart", "smallships:cog", "smallships:brigg", "smallships:galley", "smallships:drakkar", "camels:camel"]
	#
	#RangedRecruitsNeedArrowsToShoot
	#	(takes effect after restart)
	#	
	#Should ranged units need arrows to shoot?
	#If enabled ranged units will resupply arrows from upkeep chest and spawn with arrows.
	#""
	#default: false
	RangedRecruitsNeedArrowsToShoot = true
	#RecruitsChunkLoading
	#	(takes effect after restart)
	#	
	#Should recruit-companions load chunks? Disabling would make patrolling in to unloaded chunk impossible.
	#default: true
	RecruitsChunkLoading = false

#Recruit Village Config:
[Villages]
	#
	#Should Recruits instead of Iron Golems spawn in Villages
	#	(takes effect after restart)
	#	default: true
	OverrideIronGolemSpawn = false

#Recruits Equipment Config:
[Equipments]
	#
	#Following lists will be used to generate starting armor for different recruit types. Each recruit will be equipped according to a random equipment-set defined below.
	#
	#To create a equipment-set note the following order: ["main-hand", "off-hand", "feet", "legs", "chest", "head"]
	#Each set has ONLY 6 entries. Each set is separated with square brackets: RecruitStartEquipments=[[1], [2], [3], ...].
	#For example, the following configuration will randomize newly spawned recruits either 1 or 2:
	#    1. full leather armor set with wooden sword and shield.
	#    2. only gold sword.
	#
	#    RecruitStartEquipments=[["minecraft:wooden_sword", "minecraft:shield","minecraft:leather_boots","minecraft:leather_leggings","minecraft:leather_chestplate", "minecraft:leather_helmet"], ["minecraft:gold_sword", "", "", "", "", ""]]
	#
	#There is no limit of armor-sets and modded armor / weapons are also compatible. The mod item-id can be accessed with /give-command.
	#
	#
	#Recruit Start Equipments
	#Default:  [["minecraft:wooden_sword", "", "", "", "", ""], ["minecraft:stone_sword", "", "", "", "", ""]]
	#
	RecruitStartEquipments = [["minecraft:wooden_sword", "", "", "", "", ""], ["minecraft:stone_sword", "", "", "", "", ""]]
	#
	#Shieldman Start Equipments
	#Default: [["minecraft:stone_sword", "minecraft:shield", "", "", "", ""], ["minecraft:wooden_axe", "minecraft:shield", "", "", "", ""]]
	#
	ShieldmanStartEquipments = [["minecraft:stone_sword", "minecraft:shield", "", "", "", ""], ["minecraft:wooden_axe", "minecraft:shield", "", "", "", ""]]
	#
	#Bowman Start Equipments
	#Default: [["minecraft:bow", "", "", "", "", ""]]
	#
	BowmanStartEquipments = [["minecraft:bow", "", "", "", "", ""]]
	#
	#Crossbowman Start Equipments
	#Default: [["minecraft:crossbow", "", "", "", "", ""]]
	#
	CrossbowmanStartEquipments = [["minecraft:crossbow", "", "", "", "", ""]]
	#
	#Horseman Start Equipments
	#Default: [["minecraft:stone_sword", "minecraft:shield", "", "", "", ""], ["minecraft:iron_sword", "minecraft:shield", "", "", "", ""]]
	#
	HorsemanStartEquipments = [["minecraft:stone_sword", "minecraft:shield", "", "", "", ""], ["minecraft:iron_sword", "minecraft:shield", "", "", "", ""]]
	#
	#Nomad Start Equipments
	#Default: [["minecraft:bow", "", "", "", "", ""]]
	#
	NomadStartEquipments = [["minecraft:bow", "", "", "", "", ""]]

#Monster and Pillager Config:
[Hostiles]
	#
	#Should Pillagers attack Monsters
	#	(takes effect after restart)
	#	default: false
	PillagerAttackMonsters = true
	#
	#Should Monsters attack Pillagers
	#	(takes effect after restart)
	#	default: false
	MonstersAttackPillagers = true
	#
	#Should Vindicators can spawn with shield and sword and AI to use these.
	#	(takes effect after restart)
	#	default: false
	VindicatorSpawnItems = true

#Block Event Config:
[BlockEvents]
	#
	#Should Neutral Recruits attack enemy players that are placing or breaking blocks immediately?
	#	(takes effect after restart)
	#	default: true
	NeutralRecruitsBlockPlaceBreakEvents = false
	#
	#Should Neutral Recruits attack enemy players that are interacting with blocks immediately?
	#	(takes effect after restart)
	#	default: true
	NeutralRecruitsBlockInteractingEvents = false

#Recruit Patrols Config:
[Patrols]
	#
	#Should modded Pillager Patrols spawn in the world?
	#	(takes effect after restart)
	#	default: false
	ShouldPillagerPatrolsSpawn = true
	#
	#Chance that a modded Pillager Patrol can spawn. (higher values = higher chance to spawn)
	#	(takes effect after restart)
	#	default: 25.0
	#Range: 0.0 ~ 100.0
	PillagerPatrolsSpawnChance = 15.0

#General Damage Config:
[Damage]
	#List of damagesource that accept immunity
	#	(takes effect after restart)
	#	Damagesource in this list will apply a immunity of 0.5s to the entity like normal.
	AcceptedDamagesourceImmunity = ["inFire", "lava", "sweetBerryBush", "cactus", "lightningBolt", "inWall", "hotFloor", "outOfWorld", "drown"]

#Recruit Teams Config:
[Teams]
	#
	#The amount of currency needed to create a team. Set 0 to disable.
	#	(takes effect after restart)
	#	default: 10
	#Range: 0 ~ 1453
	TeamCreationCost = 0

	#Global Team Settings
	[Teams."Global Team Settings"]
		#
		#Should Recruits override following team settings on world start for all teams?
		#	(takes effect after restart)
		#	default: true
		GlobalTeamSetting = true
		#Override Friendly fire true/false for all teams on world start
		#	(takes effect after restart)
		#	default: false
		GlobalTeamFriendlyFireSetting = false
		#Override SeeFriendlyInvisible true/false for all teams on world start.
		#	(takes effect after restart)
		#	default: true
		GlobalTeamSeeFriendlyInvisibleSetting = true

	#Recruit Mod compatibility Config:
	[Teams.Compat]
		#This feature is only possible when corpse mod is installed.
		#Should recruits spawn corpse of corpse mod when dead?.
		#	(takes effect after restart)
		#	default: true
		CompatCorpseMod = false

